[package]
name = "dev-glyph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.2"
tokio = { version = "*", features = ["full"] }
tokio-postgres = "0.7.10"
chrono = { version = "0.4.31", features = [] }
crossterm = "0.27.0"